### ISSUE TITLE
nodemcu-1-door-wifimanager

### ISSUE THREAD

**Issue by andrewm659** [cedced19/garage-doors-opener#2]
Hello,
I'm trying to set this up for myself.  I loaded the noedmcu-1-door-wifimanager to my ESP8266 but I don't see where to add the Wireless config....I'm not sure it is clearly stated where to do that in the README.  I'm also a bit new to this so I might have missed something.  

Any help would be great!

**Comment by cedced19** [comment]
Hello ! This specific arduino project `noedmcu-1-door-wifimanager` do not need any wifi configuration. You just need to plug your ESP on. Then a wifi will be created only for you to enter the wireless config using your smartphone or your computer. 
Other arduino project on this repo works differently. Maybe the READMEs are not that up to date, but I will be happy to merge any suggestion.
I hope this will help.

**Comment by andrewm659** [comment]
It does help!  Any updates you can provide to make it more clear to anyone else in the future would be great.

**Comment by andrewm659** [comment]
Documentation.  Include details as to which file to use for which occasion.  Never assume.  That's my opinion.

Thanks again!  I will let you know if I need any more assistance.

**Comment by andrewm659** [comment]
So I installed the mobile app to my phone, BUT it wants the IP of the nodemcu which I can't get because I'm not setting the Wi-Fi settings in the code for the nodeMCU.  This was another step that I was a bit confused about.  

I am using JUST the ESP8266 NodeMCU device with a relay ( which I still need to purchase).

**Comment by cedced19** [comment]
If you want to set parameters by yourself your own use  [this code](https://github.com/cedced19/garage-doors-opener/blob/master/nodemcu-1-door/nodemcu-1-door.ino). 
Otherwise you should get the ip address of the nodemcu from the router.
